% --- Logger ---
[log, closeLog] = logger(fullfile('out','integration.log'),'level','INFO');
log('INFO','Starte Export...');

% --- ROS 2 (KPIs auf Topic /dtwin/kpi) ---
ros_publish(K, 'useROS2',true, 'nodeName','/dtwin', 'topic','/dtwin/kpi', ...
                'msgType','std_msgs/Float64MultiArray', 'domain',0, 'dryRun',false);

% --- OPC UA (Knoten-IDs anpassen) ---
nodeMap = struct( ...
  'picked','ns=2;s=DTwin/picked', ...
  'placed','ns=2;s=DTwin/placed', ...
  'successRate','ns=2;s=DTwin/success', ...
  'throughputPM','ns=2;s=DTwin/throughputPM', ...
  'outputRatePS','ns=2;s=DTwin/outputRatePS' ...
);
opcua_write(K, 'opc.tcp://localhost:4840', nodeMap, 'ClientName','DTwinClient', 'dryRun',true);

log('INFO','Export fertig.');
closeLog();